version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-achat
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ashrefbouden  #
      MYSQL_DATABASE: achatdb
      MYSQL_USER: ashrefbouden  
      MYSQL_PASSWORD: ashrefbouden  
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    command: --bind-address=0.0.0.0 

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile  
    image: ashrefbouden/achat-backend-ashrefbouden-4twin9
    container_name: backend-achat
    restart: always
    depends_on:
      - mysql
    ports:
      - "8089:8089"  
    volumes:
      - ./logs:/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb?useUnicode=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ashrefbouden  
      SPRING_DATASOURCE_PASSWORD: ashrefbouden  

  frontend:
    image: ashrefbouden/achat-frontend-ashrefbouden-4twin9
    container_name: frontend-achat
    ports:
      - "8082:80"  
    depends_on:
      - backend
    volumes:
      - ./logs/nginx:/var/log/nginx

volumes:
  mysql_data:
