version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-achat
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
      MYSQL_USER: achatuser
      MYSQL_PASSWORD: cyka
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --bind-address=0.0.0.0

  backend:
    image: achat-backend-gofrane-4twin9
    container_name: backend-achat
    restart: always
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    volumes:
      - ./logs:/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb?useUnicode=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: achatuser
      SPRING_DATASOURCE_PASSWORD: cyka

  frontend:
    image: dark9040/achatfrontend-chaherdridi
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./logs/nginx:/var/log/nginx
volumes:
  mysql_data:
